config/routes.rb
Base::Application.routes.draw do

  get 'logout' => 'sessions#destroy'
  get 'login' => 'sessions#new'
  get 'forgot_password' => 'password_resets#new'
  get 'reset_password/:id' => 'password_resets#edit'

  resources :sessions, only: :create
  resources :password_resets, only: [:create, :update]
  resources :addresses, only: [] do
    member do
      get 'cities'
      get 'districts'
    end
  end

  namespace :manage do
    root 'application#index'
    namespace :data do
      root 'application#index'
      resources :categories
    end
    resources :users
  end

  root 'manage/application#index'
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :contact
  belongs_to :district
end

app/models/app_config.rb
class AppConfig < Settingslogic
  config_file = File.expand_path("../../../config/app_config.yml", __FILE__)
  raise "#{config_file} not exists!" unless File.exists?(config_file)
  source config_file
  namespace Rails.env
  load!
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :province
  has_many :districts, dependent: :destroy
  validates :name, :province_id, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  has_many :addresses, dependent: :destroy
  has_one :current_address
  accepts_nested_attributes_for :addresses
end

app/models/data.rb
module Data
  def self.table_name_prefix
    'data_'
  end
end

app/models/data/category.rb
class Data::Category < ActiveRecord::Base
  self.table_name = :data_categories

  validates :name, presence: true

  scope :active, -> { where active: true }
end

app/models/district.rb
class District < ActiveRecord::Base
  belongs_to :city
  has_many :addresses
  validates :name, :city_id, presence: true
end

app/models/province.rb
class Province < ActiveRecord::Base
  has_many :cities, dependent: :destroy
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  attr_accessor :notify_user

  has_one :contact, dependent: :destroy

  validates :password, confirmation: true
  validates :password, :password_confirmation, presence: true, if: ->(u) { u.password.present? }
  validates :name, :email, presence: true
  validates :email, uniqueness: true
  accepts_nested_attributes_for :contact

  after_create :send_user_sets_password_notification
  after_update :check_and_send_user_updated_notification

  scope :search, ->(query={}){
    if query.present?
      query.symbolize_keys!
      uid = query[:id]
      email = query[:email]
      mobile_phone = query[:mobile_phone]
      name = query[:name]
      results = joins(:contact)
      results = results.where(id: uid) unless uid.blank?
      results = results.where("LOWER(users.email)=?", email.downcase) unless email.blank?
      results = results.where("contacts.mobile_phone=?", mobile_phone) unless mobile_phone.blank?
      results = results.where("LOWER(users.name) LIKE ?", "%#{name.downcase}%") unless name.blank?
      results
    end
  }

  def locked
    lock_expires_at and lock_expires_at > Time.zone.now
  end

  private

    def send_user_sets_password_notification
      set_reset_password_token
      BaseMailer.check_and_send('user_sets_password', self)
    end

    def check_and_send_user_updated_notification
      if notify_user == '1'
        BaseMailer.check_and_send('user_update_notification', self)
      end
    end

    def set_reset_password_token
      update_attribute(:reset_password_token, SecureRandom.base64(15).tr('+/=lIO0', 'pqrsxyz'))
    end

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  skip_before_action :require_login

  def cities
    @cities = City.where(province_id: params[:id])
    render text: view_context.options_from_collection_for_select(@cities, 'id', 'name')
  end

  def districts
    @districts = District.where(city_id: params[:id])
    render text: view_context.options_from_collection_for_select(@districts, 'id', 'name')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login, except: [:not_authenticated]

  protected

  def not_authenticated
    redirect_to login_path, alert: "Please login first."
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_filter :require_login
  layout 'sessions'

  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    @user.deliver_reset_password_instructions! if @user
    redirect_to(login_path, :notice => 'Instructions have been sent to your email.')
  end

  def edit
    @user = User.load_from_reset_password_token(params[:id])
    @token = params[:id]
    not_authenticated if !@user
  end

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)
    not_authenticated if !@user
    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.change_password!(params[:user][:password])
      redirect_to(root_path, :notice => 'Password was successfully updated.')
    else
      render :action => "edit"
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  layout 'sessions'

  def new
    @user = User.new
  end

  def create
    @user = login(params[:email],params[:password],params[:remember])
    if @user
      redirect_back_or_to root_path
    else
      check_login_attempt
      render :action => "new"
    end
  end

  def destroy
    logout
    redirect_to login_path, :notice => 'Logged out!'
  end

  protected

  def check_login_attempt
    @user = User.find_by_email(params[:email])
    if @user.present?
      if @user.locked
        flash.now[:error] = '您的登录失败次数过多，请在1分钟后重试'
      else
        flash.now[:error] = '用户密码错误，请重新输入密码'
      end
    else
      flash.now[:error] = '用户不存在，请检查修改您的邮箱，重新登录'
    end
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(obj)
    if obj.errors.present?
      messages = ""
      obj.errors.messages.each do |k, v|
        messages << content_tag(:li, "#{t(k)} #{v.join(',')}")
      end
      content_tag :div, class: "alert alert-danger" do
        content_tag :ul do
          messages.html_safe
        end
      end
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">ITguys base</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><%= link_to t('user'), manage_users_path %></li>
        <li><a href="#">About</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown">
              内容
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li> <%= link_to '分类管理', manage_data_categories_path %> </li>
            <li class="divder"></li>
            <li class="dropdown-header">Dropdown header</li>
            <li><a href="#">Link 4</a></li>
            <li><a href="#">Link 4</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown">
            Dropdown
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><a href="#">Link 1</a></li>
            <li><a href="#">Link 2</a></li>
            <li><a href="#">Link 3</a></li>
            <li class="divder"></li>
            <li class="dropdown-header">Dropdown header</li>
            <li><a href="#">Link 4</a></li>
            <li><a href="#">Link 4</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link 1</a></li>
        <li><a href="#">About</a></li>
        <li>
        <a class="dropdown-toggle" data-toggle="dropdown">
          <%= current_user.name %>
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to(t('logout'), '/logout')%></li>
          <li><a href="#"><%= t('settings')%></a></li>
        </ul>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Base" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div class="container-fluid">
      <div class="col-md-offset-4 col-md-4">
        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/password_resets/edit.html.erb
<div class="row">
  <%= form_for :user, url: password_reset_path, method: :patch, html: {class: 'form-horizontal', role: 'form'} do |f| %>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-6">
        <%= @user.email %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-6">
        <%= f.password_field :password, class: 'form-control', placeholder: '密码', required: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-6">
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: '重复密码', required: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-6">
        <%= submit_tag 'Reset now', class: 'btn btn-primary btn-block'%>
      </div>
    </div>
  <% end %>
</div>

app/views/password_resets/new.html.erb
<div class="row">
  <%= form_tag password_resets_path, method: :post, class: 'form-horizontal', role: 'form' do |f| %>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-8 text-center">
        <h2 class="form-group-heading"><strong>忘记密码</strong></h2>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-8">
        <%= email_field_tag :email, nil, class: 'form-control', placeholder: 'Email address', required: true, autofocus: true %>
        <%= submit_tag '发送重置请求', class: 'btn btn-primary btn-block'%>
      </div>
    </div>
  <% end -%>
</div>